keras imports for the dataset and building our neural network

In [4]:
# pip install pandas numpy matplotlib seaborn scikit-learn keras tensorflow scipy statsmodels jupyter notebook

In [1]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D, Flatten
from tensorflow.python.keras.utils.np_utils import to_categorical
from sklearn.metrics import accuracy_score

loading the dataset

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [4]:
X_train[0][1] # Completedly black

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

building the input vector from the 28x28 pixels

In [5]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

normalizing the data to help with the training

In [6]:
# Scaling data
# Make each vector in 0 to 1 
# min: 0 -> 0
# max: 255 -> 1
X_train /= 255 
X_test /= 255

one-hot encoding using keras' numpy-related utilities

In [8]:
# 6000 rows -> 6000 rows and 10 cols
# class 1: 1 0 0 0 0 ... 0
# class 2: 0 1 0 0 0 ... 0
# one hot encoding 를 사용하는 경우, 카테고리 마다 연관성이 없기 떄문에
# 콜럼 수 증가 (데이터량 증가), 눌 값 증가 (sparse; 한 값만 1, 나머지 값은 0) 

n_classes = 10
print("Shape before one-hot encoding: ", y_train.shape)
Y_train = to_categorical(y_train, n_classes)
Y_test = to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)

Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)


building a linear stack of layers with the sequential model

In [9]:
model = Sequential()
# convolutional layer
# 25: # of hidden layer?? / batch size??
# stides: 1 px move
# relu: first one to try (tend to work better)
model.add(Conv2D(25, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape=(28,28,1)))

# pooling layer
# usually 2x2 or 3x3
model.add(MaxPool2D(pool_size=(1,1)))

# flatten output of conv
model.add(Flatten())
# hidden layer
model.add(Dense(100, activation='relu'))
# output layer
model.add(Dense(10, activation='softmax'))

compiling the sequential model

In [10]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
# multi class problems
# adam - default optimizer

training the model for 10 epochs

In [11]:
model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data=(X_test, Y_test))
# batch_size=128 - 128 rows at one time
# epochs=10 - 10 times repeats
# 이폭스를 반복 할 수록 로스는 줄이고 정확도를 높이는 적이 목적

Epoch 1/10


469/469 [==============================] - 17s 33ms/step - loss: 0.1967 - accuracy: 0.9427 - val_loss: 0.0906 - val_accuracy: 0.9720
Epoch 2/10
469/469 [==============================] - 15s 32ms/step - loss: 0.0623 - accuracy: 0.9811 - val_loss: 0.0632 - val_accuracy: 0.9786
Epoch 3/10
469/469 [==============================] - 15s 32ms/step - loss: 0.0376 - accuracy: 0.9886 - val_loss: 0.0536 - val_accuracy: 0.9817
Epoch 4/10
469/469 [==============================] - 15s 32ms/step - loss: 0.0243 - accuracy: 0.9926 - val_loss: 0.0472 - val_accuracy: 0.9841
Epoch 5/10
469/469 [==============================] - 16s 34ms/step - loss: 0.0163 - accuracy: 0.9950 - val_loss: 0.0567 - val_accuracy: 0.9826
Epoch 6/10
469/469 [==============================] - 15s 33ms/step - loss: 0.0107 - accuracy: 0.9970 - val_loss: 0.0499 - val_accuracy: 0.9849
Epoch 7/10
469/469 [==============================] - 15s 32ms/step - loss: 0.0065 - accuracy: 0.9982 - val_loss: 0.0515 - val_accurac

Save the model to disk.

In [ ]:
# model.save_weights('cnn_B.h5')
# 모델 저장

Load the model from disk using later:

In [5]:
# model.load_weights('cnn_B.h5')
# 모델 불러오기

Predict on the first 5 test images.

In [12]:
predictions = model.predict(X_test [:10]) 

1/1 [==============================] - 0s 91ms/step


Print our model's predictions.

In [13]:
import numpy as np
print(np.argmax(predictions, axis=1))

[7 2 1 0 4 1 4 9 5 9]


Check our predictions against the ground truths.

In [14]:
print(y_test[:10]) 

[7 2 1 0 4 1 4 9 5 9]
